index_frontEnd:
    pattern: /
    defaults: { _controller: FrontEndBundle:Index:index }
    
login:
  pattern: /login
  defaults: { _controller: FrontEndBundle:Login:login }
  
logout:
  pattern: /logout
  defaults: { _controller: FrontEndBundle:Login:logout }

register:
  pattern: /register
  defaults: { _controller: FrontEndBundle:Register:register }
  

search:
    pattern: /search
    defaults: { _controller: FrontEndBundle:Search:search }

search_filter:
    pattern: /searchFilter
    defaults: { _controller: FrontEndBundle:Search:filter }
    
course:
  pattern: /course
  defaults: { _controller: FrontEndBundle:Course:index }
